# Generated by Django 2.2.5 on 2020-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
