# Generated by Django 2.2.5 on 2020-07-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200630_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
