# Generated by Django 2.2.5 on 2020-07-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1593686188537&di=01d5790d79716e3ba84d87282faafb53&imgtype=0&src=http%3A%2F%2Fpic.51yuansu.com%2Fpic3%2Fcover%2F03%2F59%2F66%2F5bd129fad1055_610.jpg', max_length=500, null=True),
        ),
    ]
