# Generated by Django 2.2.5 on 2020-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_del',
            field=models.IntegerField(default=0),
        ),
    ]
