# Generated by Django 2.2.5 on 2020-07-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_message_id_del'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_del',
            new_name='is_del',
        ),
    ]
