# Generated by Django 2.2.5 on 2020-07-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_del',
            field=models.IntegerField(default=0),
        ),
    ]
