# Generated by Django 2.2.5 on 2020-07-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200704_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_channel',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='art_channel',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='art_class',
            name='classify_id',
        ),
        migrations.AddField(
            model_name='art_channel',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AddField(
            model_name='art_channel',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Channel'),
        ),
        migrations.AddField(
            model_name='art_class',
            name='classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Classify'),
        ),
        migrations.AlterField(
            model_name='art_class',
            name='article_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
