# Generated by Django 2.2.5 on 2020-07-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200630_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.CharField(max_length=200, null=True, verbose_name='封面'),
        ),
    ]
