# Generated by Django 2.2.5 on 2020-07-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200704_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art_class',
            old_name='article_id',
            new_name='article',
        ),
    ]
