# Generated by Django 2.2.5 on 2020-07-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.CharField(max_length=1000, null=True, verbose_name='封面'),
        ),
    ]
