# Generated by Django 2.2.5 on 2020-07-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200701_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='channel',
            field=models.CharField(default='编程', max_length=20),
        ),
    ]
